apiVersion: v1
kind: Service
metadata:
  name: my-webapp-service
  namespace: my-app-namespace
  labels:
    app: my-webapp
spec:
  selector:
    app: my-webapp
  ports:
  - name: web
    port: 80
    targetPort: 3000
  - name: metrics
    port: 8080
    targetPort: 8080

