apiVersion: v1
kind: Service
metadata:
  name: my-webapp-service
  namespace: my-app-namespace
  labels:
    app: my-webapp
spec:
  selector:
    app: my-webapp
  ports:
    - name: http           # ⚡ Must match ServiceMonitor 'port'
      port: 8080
      targetPort: 3000     # ⚡ Your container's exposed port
      protocol: TCP
  type: ClusterIP
